### ISSUE TITLE
Version 3.0.8 missing python

### ISSUE THREAD

**Issue by lee-reinhardt** [linuxserver/docker-sonarr#216]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Python should be available within the container for custom scripts.

## Current Behavior
Python is missing from version 3.0.8

I noticed this because I recently upgraded and my custom scripts failed to launch with an err 127 command not found.

## Steps to Reproduce

1. Run a sonarr container using `lscr.io/linuxserver/sonarr:3.0.8`
2. Exec a shell in the container, `docker exec -it sonarr /bin/bash`
3. Check for python, `which python`
4. See no results

Following these steps on `3.0.7` will output the expected `/usr/bin/python`

## Environment
**OS:** Ubuntu 21.10
**CPU architecture:** x86_64
**How docker service was installed:** apt

## Command used to create docker container (run/create/compose/screenshot)

```
docker run -d \
  --name=sonarr \
  -e PUID=1000 \
  -e PGID=1000 \
  -p 8989:8989 \
  lscr.io/linuxserver/sonarr:3.0.8
```

**Comment by enchained** [comment]
Looks like the baseimage was changed to the one that does not include python: https://github.com/linuxserver/docker-sonarr/releases/tag/3.0.8.1507-ls145
Dev branch also dropped python a while ago, so I suppose recent changes are intentional.

You can try adding a docker mod to install python on top of the baseimage: https://github.com/linuxserver/docker-mods/tree/universal-package-install
In my case I just had to add two ENV vars to my linuxserver/sonarr container and my custom py script started working again.
```
DOCKER_MODS=linuxserver/mods:universal-package-install
INSTALL_PACKAGES=python
```

**Comment by lee-reinhardt** [comment]
@enchained Thank you for the easy workaround, which indeed works. I'll leave this open just for visibility to anyone else who may bump into this.

This can be closed if someone determines this is intentional.

**Comment by Quiksmage** [comment]
it looks like this docker mod does Python 2.7.18, which is awesome, but my script is python3.
Is there a way to get python 3 in a similar fashion? I was looking through the dockermods github, but I'm kind of lost D:
