### ISSUE TITLE
[BUG] Crash loop since update 

### ISSUE THREAD

**Issue by ADiEmme** [linuxserver/docker-sonarr#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

Since some of the packages have been updated inside the container, Mono keep crashing in loop.

Logs attached.
https://pastebin.com/yZc5quKY

Apparlently, i am not the only one suffering due to the last changes:
https://www.reddit.com/r/sonarr/comments/114t71x/sonarr_docker_crash_on_startup/

### Expected Behavior

No crash.

### Steps To Reproduce

Pull the image and start the container

### Environment

```markdown
- OS:
[root@amachine adiemme]# cat /etc/redhat-release
Fedora release 31 (Thirty One)
[root@amachine adiemme]# uname -r
5.8.18-100.fc31.x86_64

- How docker service was installed: Distro package's manager
```

### CPU architecture

x86-64

### Docker creation

```bash
Using a systemd unit, which pulls the image, creates and starts the container.

[Unit]
Description=Sonarr Container
Wants=network-online.target
After=network.target network-online.target

[Service]
TimeoutStartSec=0
Restart=always
ExecStartPre=-/usr/bin/podman stop %n
ExecStartPre=-/usr/bin/podman rm %n
ExecStartPre=/usr/bin/podman pull linuxserver/sonarr
ExecStart=/usr/bin/podman run --systemd=false --net host -p 8989:8989 --rm --name %n -e PUID=1100 -e PGID=1100 -e TZ=Europe/Amsterdam -v /config/sonarr:/config -v /downloads:/downloads -v /shared/tvshows:/tv  linuxserver/sonarr


[Install]
WantedBy=multi-user.target
```

### Container logs

```bash
https://pastebin.com/yZc5quKY
```

**Comment by thespad** [comment]
https://docs.linuxserver.io/faq#jammy

**Comment by ADiEmme** [comment]
Is this really how you tackle your issues and answer to people? i am not even running Ubuntu nor Docker!

**Comment by j0nnymoe** [comment]
We don't test/support our containers on podman because no one within our team runs it. I would suggest checking that your podman version is up to date or doing whatever the podman version of 
```  security_opt:
    - seccomp=unconfined``` is.

**Comment by thespad** [comment]
We could spend hours with a back and forth about how your problem is definitely something different and special despite having identical symptoms to a dozen other people who have already created issues here or on our Discord, or you could just try the very simple options provided by the FAQ entry and see if they resolve your problem or not.

Given that you're running podman rather than docker, the specific version issue obviously won't apply, but that doesn't mean that there isn't a similar issue with a given minimum version of podman that we haven't tested to establish. We have also seen previously that selinux and other Fedora/Redhat standard configurations can cause issues with seccomp profiles that necessitate additional changes.

The fact that you're not running Ubuntu is irrelevant.
