### ISSUE TITLE
Reintroducing Docker images for the armhf architecture

### ISSUE THREAD

**Issue by luckylittle** [linuxserver/docker-sonarr#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `armhf` architecture plays a crucial role in various environments, particularly those utilising ARM-based systems. Its deprecation has presented challenges for users like myself.

### Expected Behavior

Given the significance of the armhf architecture within the technology ecosystem, I kindly request that you reconsider your decision and re-add Docker images supporting this architecture.

### Steps To Reproduce

`podman pull lscr.io/linuxserver/sonarr`

```
Trying to pull lscr.io/linuxserver/sonarr:latest...
  no image found in manifest list for architecture arm, variant "v7", OS linux
Error: Error choosing an image from manifest list docker://lscr.io/linuxserver/sonarr:latest: no image found in manifest list for architecture arm, variant "v7", OS linux
```

### Environment

```markdown
- OS: Raspbian 11.5
- How docker service was installed: podman version 3.0.1
```

### CPU architecture

arm64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by thespad** [comment]
We made the decision to drop armhf support because it was no longer possible to provide images at parity with amd64 and aarch64 due to upstream distros dropping support for newer packages on the architecture. At the point we dropped armhf support, it accounted for less than 3% of our total user base, and so we concluded that the additional work required to keep the armhf images functional and running supported versions of packages was not worthwhile. That calculus has not changed, if anything it would now be even more work for even less benefit; there are vanishingly few arm devices still operating that don't support running a 64-bit OS.

You can read our original announcement [here](https://www.linuxserver.io/blog/a-farewell-to-arm-hf) for further details on the matter.
