### ISSUE TITLE
build phanton-develop (v3)

### ISSUE THREAD

**Issue by robertbaker** [linuxserver/docker-sonarr#89]

**Comment by j0nnymoe** [comment]
Already here lsiodev/sonarr-preview .

**Comment by Taloth** [comment]
@j0nnymoe We've rolled out a debian package revision, changed binaries and included debconf to specify the user.
We've also switched from `phantom` to the `phantom-develop` branch (in preparation of a separate `phantom-master` branch).
markus is already contacting you guys on discord but I figured I'd dump some details here.

For the debian package there are basically two options now:
- A [xenial](https://apt.sonarr.tv/ubuntu/dists/xenial) 'bootstrap' distro, which rarely gets updated and uses the built-in updater.
- A [xenial-develop](https://apt.sonarr.tv/ubuntu/dists/xenial-develop)/[xenial-master](https://apt.sonarr.tv/ubuntu/dists/xenial-master) distro, which gets each update and has the built-in updater disabled via a 'package_info' file in `/usr/lib/sonarr`, it also locks the branch down.

_(distros exist for ubuntu bionic and debian jesse&stretch too. But the current package is identical. We just wanted to ensure different endpoints in case we need to deal with platform specific stuff)_

It may take some work to get that functioning properly in a docker container, since the package is tailored for systemd.

The package_info has a 'UpdateMethod' property, which is set to BuiltIn for the bootstrap package or Apt for the puritan-debian package. But it can also be set to 'Docker' which will remove the 'Update' button from System->Updates and instead instruct the user to update the container when a new update is available. But i'd suggest making that a option during container creation, since some users will prefer to use the built-in updater.

Please note we moved /opt/sonarr to /usr/lib/sonarr and /var/opt/sonarr to /var/lib/sonarr after consulting the debian package guide. The package will normally migrate those files properly, but obviously the startup path is different.

Lemme know if there are questions.

**Comment by aptalca** [comment]
@Taloth just type `^readrules` in that new members channel on lsio discord to get into the public area, then we can invite you into the sonarr channel
